[package]
name = "http_snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
anyhow = "1.0.64"
itertools = "0.10.3"
rand = "0.8.5"
tokio = "1.21.0"
